default_platform(:ios)

platform :ios do

  desc "Runs the unit tests to ensure the build is working"
  lane :test do
    scan(scheme: ENV["TEST_SCHEME"], devices: ["iPhone SE"], clean: true)
  end

end
